jobs:
  install_authenticate:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
            
      - run:
          name: Login to Dev Hub
          command: |
            openssl enc -nosalt -aes-256-cbc -d -in .circleci/server.key.enc -out .circleci/server.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV
            sfdx force:auth:jwt:grant -i $DEVHUB_CONSUMER_KEY -f .circleci/server.key -u $DEVHUB_USER_NAME -d -a DevHub
      - run:
          name: List Connected Orgs
          command: sfdx force:org:list

orbs:
  salesforce-sfdx: circleci/salesforce-sfdx@2.2.0
version: 2.1
workflows:
  basic-test:
    jobs:
      - install_authenticate