jobs:
  install_authenticate:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
            
      - run:
          name: Login to Dev Hub
          command: |
            sfdx force:auth:jwt:grant -i $DEVHUB_CONSUMER_KEY -f ./data/server.key -u $DEVHUB_USER_NAME -d -a DevHub-HTS
      - run:
          name: List Connected Orgs
          command: sfdx force:org:list

orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0
version: 2.1
workflows:
  basic-test:
    jobs:
      - install_authenticate