jobs:
  install_authenticate:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
            
      - run:
          name: Login to Dev Hub
          command:
            sfdx force:auth:jwt:grant -i $HUB_CONSUMER_KEY -d -a DevHub-HTS -f ./.circleci/server.key -u $HUB_SFDX_USER
      - run:
          name: List Connected Orgs
          command: sfdx force:org:list

orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0
version: 2.1
workflows:
  basic-test:
    jobs:
      - install_authenticate